import path from 'path'
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vite.dev/config/
export default defineConfig({
  plugins: [svelte()],
  resolve: {
    alias: {
      $data: path.resolve('./src/data'),
    },
  },
  build: {
    rollupOptions: {
      output: {
        // change the name of the output files generated by `npm run build`
        entryFileNames: 'recommender.[hash].js', 
        assetFileNames: 'recommender.[hash].[ext]',
      },
    },
  },
})
