teamData = {
  "QAT": {
    "alpha3": "QAT",
    "flag": "🇶🇦",
    "name": "Qatar",
    "demonym": "Qatari",
    "foodSearch": "middle eastern",
  },
  "ECU": {
    "alpha3": "ECU",
    "flag": "🇪🇨",
    "name": "Ecuador",
    "demonym": "Ecuadorian",
    "foodSearch": "latin american",
  },
  "SEN": {
    "alpha3": "SEN",
    "flag": "🇸🇳",
    "name": "Senegal",
    "demonym": "Senegalese",
    "foodSearch": "west african",
  },
  "NED": {
    "alpha3": "NED",
    "flag": "🇳🇱",
    "name": "Netherlands",
    "demonym": "Dutch",
  },
  "ENG": {
    "alpha3": "ENG",
    "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "name": "England",
    "demonym": "English",
    "foodSearch": "british",
  },
  "IRN": {
    "alpha3": "IRN",
    "flag": "🇮🇷",
    "name": "Iran",
    "demonym": "Iranian",
    "foodSearch": "middle eastern",
  },
  "WAL": {
    "alpha3": "WAL",
    "flag": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "name": "Wales",
    "demonym": "Welsch",
    "foodSearch": "british",
  },
  "ARG": {
    "alpha3": "ARG",
    "flag": "🇦🇷",
    "name": "Argentina",
    "demonym": "Argentinian",
    "foodSearch": "latin american",
  },
  "KSA": {
    "alpha3": "KSA",
    "flag": "🇸🇦",
    "name": "Saudi Arabia",
    "demonym": "Saudi",
    "foodSearch": "middle eastern",
  },
  "MEX": {
    "alpha3": "MEX",
    "flag": "🇲🇽",
    "name": "Mexico",
    "demonym": "Mexican",
    "foodSearch": "latin american",
  },
  "POL": {
    "alpha3": "POL",
    "flag": "🇵🇱",
    "name": "Poland",
    "demonym": "Polish",
  },
  "FRA": {
    "alpha3": "FRA",
    "flag": "🇫🇷",
    "name": "France",
    "demonym": "French",
  },
  "AUS": {
    "alpha3": "AUS",
    "flag": "🇦🇺",
    "name": "Australia",
    "demonym": "Australian",
  },
  "DEN": {
    "alpha3": "DEN",
    "flag": "🇩🇰",
    "name": "Denmark",
    "demonym": "Danish",
  },
  "TUN": {
    "alpha3": "TUN",
    "flag": "🇹🇳",
    "name": "Tunisia",
    "demonym": "Tunisian",
    "foodSearch": "north african",
  },
  "ESP": {
    "alpha3": "ESP",
    "flag": "🇪🇸",
    "name": "Spain",
    "demonym": "Spanish",
  },
  "CRC": {
    "alpha3": "CRC",
    "flag": "🇨🇷",
    "name": "Costa Rica",
    "demonym": "Tico",
    "foodSearch": "latin american, costa rican",
  },
  "GER": {
    "alpha3": "GER",
    "flag": "🇩🇪",
    "name": "Germany",
    "demonym": "German",
  },
  "JPN": {
    "alpha3": "JPN",
    "flag": "🇯🇵",
    "name": "Japan",
    "demonym": "Japanese",
  },
  "BEL": {
    "alpha3": "BEL",
    "flag": "🇧🇪",
    "name": "Belgium",
    "demonym": "Belgian",
    "foodSearch": "frites",
  },
  "CAN": {
    "alpha3": "CAN",
    "flag": "🇨🇦",
    "name": "Canada",
    "demonym": "Canadian",
  },
  "MAR": {
    "alpha3": "MAR",
    "flag": "🇲🇦",
    "name": "Morocco",
    "demonym": "Moroccan",
    "foodSearch": "north african",
  },
  "CRO": {
    "alpha3": "CRO",
    "flag": "🇭🇷",
    "name": "Croatia",
    "demonym": "Croatian",
  },
  "BRA": {
    "alpha3": "BRA",
    "flag": "🇧🇷",
    "name": "Brazil",
    "demonym": "Brazilian",
    "intro": "Brazil is a soccer powerhouse, having won 5 times.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Brazil",
    "globalVoicesUrl": "https://globalvoices.org/-/world/latin-america/brazil/",
    "spotify": [{"name": "Pagode", "url": "https://open.spotify.com/playlist/3U903ICkXhjRoPgPrG4O1j"},
                {"name": "Samba", "url": "https://open.spotify.com/playlist/3xh2sgnL4trGV8rlHTfjgv"}],
    "recipeUrl": "https://www.epicurious.com/search/brazilian",
  },
  "SRB": {
    "alpha3": "SRB",
    "flag": "🇷🇸",
    "name": "Serbia",
    "demonym": "Serbian",
    "foodSearch": "balkan",
  },
  "SUI": {
    "alpha3": "SUI",
    "flag": "🇨🇭",
    "name": "Switzerland",
    "demonym": "Swiss",
  },
  "CMR": {
    "alpha3": "CMR",
    "flag": "🇨🇲",
    "name": "Cameroon",
    "demonym": "Cameroonian",
    "foodSearch": "west african",
  },
  "POR": {
    "alpha3": "POR",
    "flag": "🇵🇹",
    "name": "Portugal",
    "demonym": "Portuguese",
  },
  "GHA": {
    "alpha3": "GHA",
    "flag": "🇬🇭",
    "name": "Ghana",
    "demonym": "Ghanian",
    "foodSearch": "west african",
  },
  "URU": {
    "alpha3": "URU",
    "flag": "🇺🇾",
    "name": "Uruguay",
    "demonym": "Uruguayan",
    "foodSearch": "latin american",
  },
  "KOR": {
    "alpha3": "KOR",
    "flag": "🇰🇷",
    "name": "South Korea",
    "demonym": "Korean",
  },
};
