name: Bluesky Zipcode Bot

on:
  # schedule:
  #   - cron: '*/8 * * * *'
  workflow_dispatch:  # allows manually-triggered runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: bskybot
        run: pip install -r requirements.txt

      - name: Run bot
        working-directory: bskybot
        env:
          BSKY_HANDLE:        ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD:  ${{ secrets.BSKY_APP_PASSWORD }}
          GH_TOKEN:           ${{ secrets.GH_TOKEN }}
          GIST_ID:            ${{ secrets.GIST_ID }}
        run: python bot.py
